export const categories = [
  "Life",
  "Death",
  "Relationships",
  "Purpose",
  "Fear",
  "Memory",
  "Identity",
  "Change",
  "Loss",
  "Joy",
] as const;

export type Category = (typeof categories)[number];

export const prompts: Record<Category, string[]> = {
  Life: [
    "What does an ordinary Tuesday teach you about yourself?",
    "Describe the last moment you felt fully awake.",
    "What are you building that no one else can see?",
    "Write about something you do every day without thinking.",
    "What would you do if you had one year left with perfect health?",
    "Describe a stranger who changed your day without knowing it.",
    "What have you outgrown but haven't let go of yet?",
    "Write about a meal that meant more than food.",
    "What does your body know that your mind ignores?",
    "Describe the life you're living versus the one you imagined.",
  ],
  Death: [
    "Write a letter to someone you'll never see again.",
    "What do you want people to misremember about you?",
    "Describe something that ended before you were ready.",
    "What would you do today if you weren't afraid of dying?",
    "Write about an object you want to outlive you.",
    "What have you already let die that needed to?",
    "Describe the last time you thought about your own mortality.",
    "What would you tell your younger self about endings?",
    "Write about something that only exists because something else ended.",
    "What do you hope your last ordinary day looks like?",
  ],
  Relationships: [
    "Describe someone you love without using their name or relation to you.",
    "What conversation are you avoiding and why?",
    "Write about a silence that said more than words.",
    "Who do you owe an apology you'll probably never give?",
    "Describe a relationship that changed when no one was watching.",
    "What have you learned about love that you wish you hadn't?",
    "Write about someone who knew you before you knew yourself.",
    "What do you give to others that you won't give yourself?",
    "Describe the moment a friendship became real.",
    "Who do you need that you pretend you don't?",
  ],
  Purpose: [
    "What would you do if no one ever found out?",
    "Describe the last time you felt useful.",
    "What work would you do for free? What does that tell you?",
    "Write about something you're good at that doesn't matter to anyone else.",
    "What question are you trying to answer with your life?",
    "Describe a moment when you felt like you were exactly where you should be.",
    "What have you been preparing for without realizing it?",
    "Write about something small you do that might matter more than you think.",
    "What would you create if talent weren't a factor?",
    "Describe what success looks like when no one is watching.",
  ],
  Fear: [
    "What are you afraid of that you've never said out loud?",
    "Describe the last time fear made a decision for you.",
    "What would you attempt if you knew you'd fail but no one would know?",
    "Write about something you're afraid to want.",
    "What fear have you inherited from someone else?",
    "Describe a fear you've outgrown and how it happened.",
    "What are you more afraid of—being seen or being invisible?",
    "Write about something you do to feel safe that might not be helping.",
    "What would courage look like in your life this week?",
    "Describe the fear that lives closest to your hope.",
  ],
  Memory: [
    "Describe a memory that changes each time you visit it.",
    "What do you remember that no one else does?",
    "Write about a smell that takes you somewhere specific.",
    "What have you forgotten that you wish you could remember?",
    "Describe a memory you're not sure actually happened.",
    "What do you remember about a place that no longer exists?",
    "Write about the first time you realized adults didn't have answers.",
    "What memory do you return to when you need to feel like yourself?",
    "Describe something you remember wrong on purpose.",
    "What would you give to forget one thing completely?",
  ],
  Identity: [
    "Who are you when no one needs anything from you?",
    "Describe a label you've accepted that doesn't quite fit.",
    "What part of yourself have you hidden to make others comfortable?",
    "Write about who you were before you learned to perform.",
    "What would you have to give up to become who you want to be?",
    "Describe the version of yourself you show to strangers.",
    "What have you changed about yourself that you miss?",
    "Write about something true about you that surprises people.",
    "Who would you be if you'd grown up somewhere else?",
    "Describe the gap between who you are and who you pretend to be.",
  ],
  Change: [
    "What are you in the middle of becoming?",
    "Describe a change you made that no one noticed.",
    "What have you been putting off that would change everything?",
    "Write about something you thought was permanent until it wasn't.",
    "What change are you resisting that might be good for you?",
    "Describe the last time you surprised yourself.",
    "What would have to change for you to feel free?",
    "Write about a small shift that led somewhere unexpected.",
    "What are you holding onto that's holding you back?",
    "Describe the person you're slowly becoming.",
  ],
  Loss: [
    "What have you lost that you didn't value until it was gone?",
    "Describe an empty space that used to be full.",
    "Write about something you lost that made room for something else.",
    "What loss taught you the most about yourself?",
    "Describe the last time you grieved something that wasn't a death.",
    "What are you losing slowly that you pretend not to notice?",
    "Write about something you lost that you hope someone else found.",
    "What would you go back and hold onto longer if you could?",
    "Describe a loss that eventually felt like relief.",
    "What have you lost that still shapes your days?",
  ],
  Joy: [
    "Describe the last time you laughed without thinking about it.",
    "What makes you happy that you're almost embarrassed to admit?",
    "Write about a moment of unexpected joy in an ordinary day.",
    "What did you love as a child that you've stopped allowing yourself?",
    "Describe someone else's joy that made you feel something.",
    "What would you do more of if you weren't worried about being productive?",
    "Write about a place where you feel lighter.",
    'What joy have you been postponing for the "right time"?',
    "Describe something simple that reliably makes your day better.",
    "What would your life look like if you optimized for joy?",
  ],
};
